//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BYOCCore.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BYOCCore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to p	pc	output	FTC	x	x	x	x
        ///s	mem	loadmar	FTC	x	x	x	x
        ///p	mem	output	FTC	x	x	x	x
        ///s	regi	load	FTC	x	x	x	x
        ///p	rega	output	TAB	x	x	x	x
        ///s	regb	load	TAB	x	x	x	x
        ///s	regi	reset	TAB	x	x	x	x
        ///s	pc	count	TAB	x	x	x	x
        ///p	regb	output	TBA	x	x	x	x
        ///s	rega	load	TBA	x	x	x	x
        ///s	regi	reset	TBA	x	x	x	x
        ///s	pc	count	TBA	x	x	x	x
        ///p	alu	add	ADD	x	x	x	x
        ///s	rega	load	ADD	x	x	x	x
        ///s	regi	reset	ADD	x	x	x	x
        ///s	pc	count	ADD	x	x	x	x
        ///p	alu	sub	SUB	x	x	x	x
        ///s	rega	load	SUB	x	x	x	x
        ///s	regi	reset	SUB	x	x	x	x
        ///s	pc	count	SUB	x	x	x	x
        ///p	pc	coun [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string currentrom {
            get {
                return ResourceManager.GetString("currentrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	LAI	#15
        ///	PSA
        ///	POB
        ///	LRA	letter
        ///	LRB	one
        ///	PSA
        ///loop:	ADD
        ///	PSA
        ///	JMP	loop
        ///letter:	.BYTE	#65
        ///one:	.BYTE	#1
        ///.
        /// </summary>
        internal static string examplesrc {
            get {
                return ResourceManager.GetString("examplesrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Temp {
            get {
                return ResourceManager.GetString("Temp", resourceCulture);
            }
        }
    }
}
